# +-------------------------------------------------------------------+
# <                               CEDIT                               >
# <                       STANDARD CONFIG FILE                        >
# +-------------------------------------------------------------------+

# +-------------------------------------------------------------------+
# <                              CEdit                                >
# <              A plugin which lets you map new commands             >
# <                      to existing ones.                            >
# +-------------------------------------------------------------------+

# +-------------------------------------------------------------------+
# <                           PARAMETERS                              >
# <        FromCommand : The command you want to be executed.         >
# <          ToCommand : The command you want to type.                >
# +-------------------------------------------------------------------+

cedit:
  fromcommand:
    - warp shop
    - warp hub
  tocommand:
    - shop
    - hub