main: me.WASDHelioS.Main.Main
name: CEdit
version: 0.29
author: HelioS_HT
description: -Lets you handle your commands.-
commands:
  cedit:
    description: placeholder
    usage: /cedit
  cedit help:
    description: returns help message
    usage: /cedit help
  cedit ?:
    description: returns help message
    usage: /cedit ?
  cedit list:
    description: returns a list of all commands.
    usage: /cedit list
  cedit reload:
    description: Reloads the config file.
    usage: /cedit reload
  cedit add /[fromcommand] /[tocommand]:
    description: adds a new command from + to
    usage: /cedit add /[fromcommand] /[tocommand]
  cedit edit /[fromcommand] /[tocommand] /[new fromcommand] /[new tocommand]:
    description: edits a command to something else.
    usage: /cedit edit /[fromcommand] /[tocommand] /[newFromcommand] /[newTocommand]
  cedit edit index <index> /[fromcommand] /[tocommand]:
    description: edits a command to something else based on the index.
    usage: /cedit edit 
  cedit remove fromc [fromcommand]:
    description: removes the fromcommand and tocommand based on fromcommand.
    usage: /cedit remove from [fromcommand]
  cedit remove toc [tocommand]:
    description: removes the tocommand and fromcommand based on tocommand.
    usage: /cedit remove to [tocommand]
  cedit remove index [index]:
    description: removes the tocommand and fromcommand based on index.
    usage: /cedit remove index [index]
    #OTHER
    
    
    ##PERMISSIONS##
    
permissions:
  
  cedit.*:
    description: Gives access to all the commands.
    children:
      cedit.add: true
      cedit.reload: true
      cedit.edit: true
      cedit.remove: true
  cedit.add:
    description: adds a command.
    default: op

  cedit.reload:
    description: reloads CEdit.
    default: op
    
  cedit.edit:
    description: edits a command.
    default: op
    
  cedit.remove:
    description: removes a command.
    default: op
    