main: me.WASDHelioS.Main.Main
name: CEdit
version: 0.11
author: HelioS_HT
description: -Lets you handle your commands.-
commands:
  cedit:
    description: placeholder
    usage: /cedit
    
  cedit help:
    description: returns help message
    usage: /cedit help
  cedit ?:
    description: returns help message
    usage: /cedit ?
  cedit list:
    description: returns a list of all commands.
    usage: /cedit list
  cedit add fromc [fromcommand] toc [tocommand]:
    description: adds a new command from + to
    usage: /cedit add from [fromcommand] to [tocommand]
  cedit edit fromc [fromcommand] toc [tocommand] newfromc [fromcommand] newtoc [tocommand]:
    description: edits a command to something else.
    usage: /cedit edit /[fromcommand] /[tocommand] /[newFromcommand] /[newTocommand]
  cedit remove fromc [fromcommand]:
    description: removes the fromcommand and tocommand based on fromcommand.
    usage: /cedit remove from [fromcommand]
  cedit remove toc [tocommand]:
    description: removes the tocommand and fromcommand based on tocommand.
    usage: /cedit remove to [tocommand]
    #OTHER
    
    
    ##PERMISSIONS##
    
permissions:
  helios.*:
    description: Gives access to all commands
    children:
      helios.standardUse: true
      helios.manipulationUse: true
      helios.opCommands: true
  helios.standardUse:
    description: the standard toggle and stuff for poke.
    default: true
  helios.manipulationUse:
    description: manipulation of other players' poke function.
    default: op
  helios.opCommands:
    description: all the other commands plebians should not be able to use.
    default: op
    
      